export const mockCurrentUser = {
  id: 1,
  uuid: 'usr-rian-001',
  name: 'Rian Pratama',
  email: 'rian@intelecta.id',
  phone: '+6281122334455',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
  status: 'active',
  role: 'Lead Fullstack Engineer',
};

export const mockTeam = [
  {
    id: 1,
    uuid: 'usr-rian-001',
    name: 'Rian Pratama',
    email: 'rian@intelecta.id',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    status: 'active',
    team_profile: {
      slug: 'rian-pratama',
      job_title: 'Senior Fullstack & WebApp Lead',
      tagline: 'Architecting resilient SaaS & high-load distributed systems.',
      bio_id: 'Berpengalaman lebih dari 8 tahun dalam merancang arsitektur cloud modular, REST/GraphQL API berskala tinggi dengan Laravel & Node.js, serta frontend modern React & Next.js.',
      skills_json: ['Laravel 11', 'React 19', 'Next.js 15', 'PostgreSQL', 'Redis', 'Docker', 'Kubernetes'],
      certifications_json: [
        { name: 'AWS Certified Solutions Architect', year: '2025' },
        { name: 'Meta Certified Fullstack Engineer', year: '2024' }
      ],
      social_links_json: {
        github: 'https://github.com/rianintelecta',
        linkedin: 'https://linkedin.com/in/rianpratama',
      },
      is_public_showcase: true,
      display_order: 1,
    },
    active_tasks_count: 2,
  },
  {
    id: 2,
    uuid: 'usr-sarah-002',
    name: 'Sarah Dian',
    email: 'sarah@intelecta.id',
    avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&auto=format&fit=crop&q=80',
    status: 'active',
    team_profile: {
      slug: 'sarah-dian',
      job_title: 'Lead Mobile App Engineer (iOS & Flutter)',
      tagline: 'Crafting buttery smooth native-feel mobile experiences.',
      bio_id: 'Spesialis mobile multi-platform Flutter, Kotlin, dan Swift dengan fokus pada optimasi 120Hz frame rate, offline-first sync architecture, serta integrasi hardware BLE dan payment SDK.',
      skills_json: ['Flutter', 'Dart', 'Swift', 'Kotlin', 'Firebase SDK', 'Fastlane', 'CI/CD Mobile'],
      certifications_json: [
        { name: 'Google Associate Android Developer', year: '2024' },
      ],
      social_links_json: {
        github: 'https://github.com/sarahmobile',
        linkedin: 'https://linkedin.com/in/sarahdian',
      },
      is_public_showcase: true,
      display_order: 2,
    },
    active_tasks_count: 1,
  },
  {
    id: 3,
    uuid: 'usr-dimas-003',
    name: 'Dimas Arya',
    email: 'dimas@intelecta.id',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    status: 'active',
    team_profile: {
      slug: 'dimas-arya',
      job_title: 'Senior Frontend & Design Engineer',
      tagline: 'Bridging the gap between high aesthetics and snappy web performance.',
      bio_id: 'Fokus pada desain sistem modern bernuansa dark aesthetic, micro-animations Framer Motion, accessibility WCAG 2.1, dan web core vitals score 99+.',
      skills_json: ['React 19', 'Tailwind CSS', 'TypeScript', 'Framer Motion', 'Figma Tokens', 'Vite'],
      certifications_json: [
        { name: 'Interaction Design Specialist', year: '2025' },
      ],
      social_links_json: {
        github: 'https://github.com/dimasui',
        linkedin: 'https://linkedin.com/in/dimasarya',
      },
      is_public_showcase: true,
      display_order: 3,
    },
    active_tasks_count: 1,
  }
];

export const mockClients = [
  {
    id: 1,
    uuid: 'cl-fintech-01',
    company_name: 'PT FinTech Nusantara Mandiri',
    pic_name: 'Hendrawan Kusuma',
    pic_email: 'hendrawan@fintechnusantara.co.id',
    pic_phone: '+628119008877',
    pic_position: 'Chief Technology Officer (CTO)',
    industry: 'Financial Technology & Banking',
    website: 'https://fintechnusantara.co.id',
    tax_id: '01.234.567.8-012.000',
    address: 'Menara Mandiri Lt. 24, Jl. Jend. Sudirman Kav. 54-55, Jakarta Selatan',
    notes: 'Klien enterprise tier-1 dengan SLA 99.99% dan audit keamanan reguler.',
    created_at: '2026-06-15T09:00:00Z',
  },
  {
    id: 2,
    uuid: 'cl-logistik-02',
    company_name: 'PT Logistik Global Express',
    pic_name: 'Budi Santoso',
    pic_email: 'budi.s@globalexpress.id',
    pic_phone: '+6281233445566',
    pic_position: 'Head of Digital Innovation',
    industry: 'Supply Chain & Logistics',
    website: 'https://globalexpress.id',
    tax_id: '02.987.654.3-034.000',
    address: 'Kawasan Pergudangan Soewarna Blok D, Bandara Soekarno Hatta, Tangerang',
    notes: 'Proyek tracking kurir armada realtime GPS BLE.',
    created_at: '2026-07-01T10:30:00Z',
  },
  {
    id: 3,
    uuid: 'cl-medika-03',
    company_name: 'PT Medika Sehat Digital',
    pic_name: 'dr. Anita Wijaya, Sp.A',
    pic_email: 'anita.wijaya@medikasehat.co.id',
    pic_phone: '+6281577889900',
    pic_position: 'Managing Director',
    industry: 'Healthcare & Telemedicine',
    website: 'https://medikasehat.co.id',
    tax_id: '03.456.789.1-056.000',
    address: 'Kuningan Cyber Building Lt. 10, Jl. HR Rasuna Said, Jakarta Selatan',
    notes: 'Platform konsultasi dokter video call WebRTC terenkripsi HIPAA compliant.',
    created_at: '2026-07-20T14:15:00Z',
  },
];

export const mockProjects = [
  {
    id: 1,
    uuid: 'proj-ft-web-01',
    client_id: 1,
    client: mockClients[0],
    project_code: 'INTL-2026-001',
    title: 'Core Banking API & SaaS Partner Portal',
    category: 'webapp_development',
    status: 'active_sprint',
    contract_value: 350000000,
    start_date: '2026-08-01',
    target_completion_date: '2026-11-30',
    git_repository_url: 'https://github.com/intelecta-org/fintech-core-portal',
    staging_url: 'https://staging-portal.fintechnusantara.intelecta.dev',
    production_url: 'https://portal.fintechnusantara.co.id',
    description: 'Pengembangan portal multi-tenant B2B untuk integrasi open banking API, disbursement otomatis, dan rekonsiliasi mutasi bank.',
  },
  {
    id: 2,
    uuid: 'proj-lg-mob-02',
    client_id: 2,
    client: mockClients[1],
    project_code: 'INTL-2026-002',
    title: 'Global Express Driver & Fleet App',
    category: 'mobile_app_development',
    status: 'active_sprint',
    contract_value: 185000000,
    start_date: '2026-08-10',
    target_completion_date: '2026-10-25',
    git_repository_url: 'https://github.com/intelecta-org/globalexpress-mobile',
    staging_url: 'https://app-dist.intelecta.dev/globalexpress-beta',
    production_url: '',
    description: 'Aplikasi seluler Flutter untuk 1.500+ kurir lapangan dengan routing navigasi offline, barcode scan camera OCR, dan e-signature bukti kirim.',
  },
  {
    id: 3,
    uuid: 'proj-md-web-03',
    client_id: 3,
    client: mockClients[2],
    project_code: 'INTL-2026-003',
    title: 'Medika Sehat Telehealth Platform',
    category: 'web_development',
    status: 'uat',
    contract_value: 120000000,
    start_date: '2026-07-25',
    target_completion_date: '2026-09-15',
    git_repository_url: 'https://github.com/intelecta-org/medika-telehealth-web',
    staging_url: 'https://staging.medikasehat.intelecta.dev',
    production_url: '',
    description: 'Web portal modern Next.js 15 dengan integrasi antrean dokter real-time Firestore dan pembayaran otomatis Snap Midtrans.',
  },
];

export const mockTasks = [
  {
    id: 1,
    uuid: 'tsk-001',
    project_id: 1,
    project_code: 'INTL-2026-001',
    title: 'Setup HMAC SHA-256 Webhook Ingestion Validator',
    description: 'Implementasi middleware validasi signature request webhook dari bank partner dengan timing attack resistant string comparison.',
    status: 'done',
    priority: 'high',
    story_points: 5,
    assigned_to_user_id: 1,
    assignee: mockTeam[0],
    due_date: '2026-08-25',
  },
  {
    id: 2,
    uuid: 'tsk-002',
    project_id: 1,
    project_code: 'INTL-2026-001',
    title: 'Idempotency Key Cache Handler di Redis Cluster',
    description: 'Memastikan request transfer dana duplikat dicegah secara otomatis menggunakan atomic lock Redis 60 detik.',
    status: 'in_progress',
    priority: 'urgent',
    story_points: 8,
    assigned_to_user_id: 1,
    assignee: mockTeam[0],
    due_date: '2026-09-02',
  },
  {
    id: 3,
    uuid: 'tsk-003',
    project_id: 2,
    project_code: 'INTL-2026-002',
    title: 'Optimasi Battery-Drain Background GPS Tracking di Flutter',
    description: 'Konfigurasi geofencing dan fused location provider agar konsumsi baterai kurir tetap di bawah 4% per jam saat tracking aktif.',
    status: 'in_progress',
    priority: 'high',
    story_points: 8,
    assigned_to_user_id: 2,
    assignee: mockTeam[1],
    due_date: '2026-09-05',
  },
  {
    id: 4,
    uuid: 'tsk-004',
    project_id: 3,
    project_code: 'INTL-2026-003',
    title: 'Pemeriksaan UAT Video Call WebRTC di Browser Safari iOS',
    description: 'Verifikasi audio echo cancellation dan fallback ICE server TURN relay untuk koneksi jaringan telco 4G.',
    status: 'review_uat',
    priority: 'medium',
    story_points: 3,
    assigned_to_user_id: 3,
    assignee: mockTeam[2],
    due_date: '2026-09-01',
  },
  {
    id: 5,
    uuid: 'tsk-005',
    project_id: 1,
    project_code: 'INTL-2026-001',
    title: 'Audit Trail Export ke Format CSV & PDF Terenkripsi',
    description: 'Fitur ekspor mutasi dan log akses pengguna untuk kepatuhan regulasi OJK & ISO 27001.',
    status: 'todo',
    priority: 'medium',
    story_points: 5,
    assigned_to_user_id: 3,
    assignee: mockTeam[2],
    due_date: '2026-09-10',
  },
];

export const mockLeads = [
  {
    id: 1,
    uuid: 'lead-ig-01',
    source: 'instagram_dm',
    sender_name: 'Bintang Radiance (@bintang_tech)',
    sender_contact: '@bintang_tech (IG Direct)',
    company_name: 'Radiance Digital Media',
    subject_or_intent: 'Tanya Paket WebApp SaaS & Mobile App MVP',
    initial_message: 'Halo tim Intelecta! Kami tertarik untuk buat platform marketplace custom untuk kreator konten di Indonesia. Butuh web portal admin dan aplikasi mobile iOS/Android. Apakah bisa konsultasi sprint dan perkiraan estimasi biayanya?',
    ai_sentiment_score: 0.94,
    ai_suggested_reply: 'Halo Kak Bintang! Terima kasih atas ketertarikan Anda pada Intelecta. Kami siap membantu mewujudkan marketplace kreator Anda dengan solusi WebApp modern dan Mobile App Flutter berkinerja tinggi. Bisakah kami menjadwalkan sesi discovery call singkat selama 20 menit besok pukul 14.00 WIB untuk membahas spesifikasi teknis dan estimasi sprint MVP Anda?',
    status: 'new',
    created_at: '2026-08-31T09:12:00Z',
  },
  {
    id: 2,
    uuid: 'lead-cli-02',
    source: 'web_terminal_cli',
    sender_name: 'Arif Wibowo (CTO Startup)',
    sender_contact: 'arif.w@aerologix.id',
    company_name: 'AeroLogix Indonesia',
    subject_or_intent: 'Terminal Ingestion: command `services --mobile --quote`',
    initial_message: 'Pengunjung mengeksekusi terminal CLI interaktif pada landing page Intelecta: `services --mobile-app --scale --quote`. Kebutuhan: Telemetri IoT & Dashboard Mobile armada drone.',
    ai_sentiment_score: 0.88,
    ai_suggested_reply: 'Halo Pak Arif, kami mendeteksi interaksi Anda melalui terminal CLI Intelecta mengenai solusi Mobile App IoT Telemetri. Tim engineering mobile kami memiliki rekam jejak kuat dalam arsitektur real-time telemetri. Kami dapat mengirimkan executive whitepaper dan proposal teknis arsitektur hari ini.',
    status: 'qualified',
    created_at: '2026-08-31T08:45:00Z',
  },
  {
    id: 3,
    uuid: 'lead-form-03',
    source: 'web_contact_form',
    sender_name: 'Clara Setya',
    sender_contact: 'clara@nusantarawealth.com',
    company_name: 'Nusantara Wealth Management',
    subject_or_intent: 'Revamp Company Profile & Investor Portal',
    initial_message: 'Selamat pagi, kami ingin merombak total website perusahaan kami dengan desain ultra-modern, dark mode bernuansa eksklusif, serta portal login aman untuk para investor private equity.',
    ai_sentiment_score: 0.91,
    ai_suggested_reply: 'Selamat pagi Ibu Clara. Layanan Web Development Intelecta berfokus pada desain monokromatik berkelas, performa Next.js 15 berkecepatan sub-detik, serta keamanan data investor berstandar enterprise. Kami siap mengirimkan portofolio relevan dan outline sprint untuk Nusantara Wealth Management.',
    status: 'pitching',
    created_at: '2026-08-30T16:20:00Z',
  },
];

export const mockInvoices = [
  {
    id: 1,
    uuid: 'inv-001',
    client_id: 1,
    client: mockClients[0],
    project_id: 1,
    project: mockProjects[0],
    invoice_number: 'INV/2026/08/001',
    title: 'Termin 1 (DP 40%): Architecture Setup & Sprint 1 Deliverables',
    amount: 140000000,
    tax_amount: 15400000,
    total_payable: 155400000,
    payment_status: 'paid',
    due_date: '2026-08-15',
    paid_at: '2026-08-14T11:30:00Z',
    payment_gateway_ref: 'MID-TRANS-20260814-0988',
    notes: 'Pembayaran diterima via Transfer Bank Mandiri Virtual Account (Lunas).',
  },
  {
    id: 2,
    uuid: 'inv-002',
    client_id: 2,
    client: mockClients[1],
    project_id: 2,
    project: mockProjects[1],
    invoice_number: 'INV/2026/08/002',
    title: 'Termin 1 (DP 50%): Mobile App UI/UX & Flutter Scaffold',
    amount: 92500000,
    tax_amount: 10175000,
    total_payable: 102675000,
    payment_status: 'paid',
    due_date: '2026-08-20',
    paid_at: '2026-08-19T15:45:00Z',
    payment_gateway_ref: 'MID-TRANS-20260819-1124',
    notes: 'Pembayaran diterima via BCA Virtual Account.',
  },
  {
    id: 3,
    uuid: 'inv-003',
    client_id: 3,
    client: mockClients[2],
    project_id: 3,
    project: mockProjects[2],
    invoice_number: 'INV/2026/08/003',
    title: 'Termin 2 (Pelunasan 50%): UAT Completion & Handover Medika Sehat',
    amount: 60000000,
    tax_amount: 6600000,
    total_payable: 66600000,
    payment_status: 'pending_gateway',
    due_date: '2026-09-05',
    paid_at: null,
    payment_gateway_ref: 'MID-TRANS-20260831-7782',
    notes: 'Menunggu konfirmasi approval termin UAT dari direksi Medika Sehat.',
  },
];

export const mockTickets = [
  {
    id: 1,
    uuid: 'tkt-001',
    ticket_code: 'TCK-2026-089',
    client_id: 1,
    client: mockClients[0],
    project_id: 1,
    project: mockProjects[0],
    title: 'High Latency pada Endpoint /api/v1/disbursement/bulk',
    description: 'Pihak treasury klien melaporkan waktu respons transaksi batch di atas 4.5 detik saat memproses 500 records secara bersamaan.',
    priority: 'critical_sla_1hr',
    status: 'investigating',
    sla_target_at: '2026-08-31T19:45:00Z',
    assigned_engineer_id: 1,
    assigned_engineer: mockTeam[0],
    replies: [
      {
        id: 1,
        user: mockTeam[0],
        message: 'Sedang memeriksa query database N+1 pada relasi akun rekening bank penerima dan menambahkan batch insert chunk size 100.',
        is_internal_note: true,
        created_at: '2026-08-31T18:50:00Z',
      },
    ],
  },
  {
    id: 2,
    uuid: 'tkt-002',
    ticket_code: 'TCK-2026-090',
    client_id: 2,
    client: mockClients[1],
    project_id: 2,
    project: mockProjects[1],
    title: 'Request Penambahan Format Barcode Code-128 pada Scanner Kurir',
    description: 'Driver meminta dukungan scan resi tipe Code-128 selain QR Code standar untuk gudang logistik regional Jawa Timur.',
    priority: 'medium',
    status: 'open',
    sla_target_at: '2026-09-02T10:00:00Z',
    assigned_engineer_id: 2,
    assigned_engineer: mockTeam[1],
    replies: [],
  },
];

export const mockChatChannels = [
  {
    id: 'general',
    name: 'internal-ops',
    title: 'Intelecta Internal Operations',
    description: 'Channel koordinasi harian seluruh engineer dan manajemen.',
    unread_count: 0,
    last_message: 'Halo tim, sprint 2 deployment on track!',
    last_time: '18:40',
    messages: [
      {
        id: 'msg-1',
        sender_id: 'usr-rian-001',
        sender_name: 'Rian Pratama',
        sender_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
        text: 'Selamat sore rekan-rekan. Seluruh webhook Meta Graph API dan Corporate Web Next.js sudah aktif termonitor.',
        is_internal_note: false,
        time: '17:30',
      },
      {
        id: 'msg-2',
        sender_id: 'usr-sarah-002',
        sender_name: 'Sarah Dian',
        sender_avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&auto=format&fit=crop&q=80',
        text: 'Build Flutter driver app untuk Global Express sudah kami upload ke staging distribution portal.',
        is_internal_note: false,
        time: '18:15',
      },
    ],
  },
  {
    id: 'proj_INTL-2026-001',
    name: 'proj-fintech-core',
    title: 'PT FinTech Nusantara (INTL-2026-001)',
    description: 'Channel pengerjaan sprint Core Banking API & Partner Portal.',
    unread_count: 1,
    last_message: 'Ticket SLA P1 sedang diinvestigasi untuk optimasi query batch.',
    last_time: '18:52',
    messages: [
      {
        id: 'msg-p1',
        sender_id: 'usr-rian-001',
        sender_name: 'Rian Pratama',
        sender_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
        text: 'Sedang meninjau log transaksi disbursement untuk perbaikan ticket #TCK-2026-089.',
        is_internal_note: true,
        time: '18:52',
      },
    ],
  },
];
